/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package loseitcalorie;

import javafx.application.Application;
import javafx.stage.Stage;
import loseitcalorie.config.DbConfig;
import loseitcalorie.scenes.HomeScene;

public class App extends Application {
    
    @Override
    public void start(Stage stage) {
        stage.setResizable(false);
        stage.setTitle("Lose it Calorie");

        HomeScene homeScene = new HomeScene(stage);
        homeScene.showHomeScene();
        DbConfig.getConnection();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
